
project_id = "uxvhloltifucsvgawnce"

[functions]
[functions.sentiment-analysis]
[functions.deduplicate-reviews]
[functions.moderate-review]
[functions.generate-review-summary]
[functions.send-confirmation-email]

