// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxvhloltifucsvgawnce.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4dmhsb2x0aWZ1Y3N2Z2F3bmNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NzgzNTMsImV4cCI6MjA2MDU1NDM1M30.6ILP_3coJlph8rmYx2Fv0XDG0sp8JbCKuYZYHT71sq0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);